#%RAML 1.0 DataType
properties:
  id:
    type: string
    example: "456y"
  name:
    type: string
    example: "WWV"
  songIds:
    type: string[]
    example: ["123s1","123s2","123s3","123s4","123s5"]
    required: true
    minItems: 1
  artistId:
    type: string[]
    example: ["SST","DSP","MMK","HRJ","VCS"]
    minItems: 1

