#%RAML 1.0 DataType
properties:
  id:
    type: string
    example: "45BSP"
  title:
    type: string
    example: "45hyut"
    required: true
  duration:
    type: string
    example: "02:00"
    required: true
  created:
    type: date-only
    example: 2023-08-03
    required: false
  albumId:
    type: string
    example: "WWV"
    required: false

